2023-04-09 18:03:31,184 INFO    StreamThr :4936 [internal.py:wandb_internal():88] W&B internal server running at pid: 4936, started at: 2023-04-09 18:03:31.182538
2023-04-09 18:03:31,186 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: status
2023-04-09 18:03:31,188 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: status
2023-04-09 18:03:31,189 DEBUG   SenderThread:4936 [sender.py:send():303] send: header
2023-04-09 18:03:31,189 INFO    WriterThread:4936 [datastore.py:open_for_write():75] open: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/run-wdce65bh.wandb
2023-04-09 18:03:31,190 DEBUG   SenderThread:4936 [sender.py:send():303] send: run
2023-04-09 18:03:31,818 INFO    SenderThread:4936 [dir_watcher.py:__init__():216] watching files in: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files
2023-04-09 18:03:31,818 INFO    SenderThread:4936 [sender.py:_start_run_threads():928] run started: wdce65bh with start time 1681056210.189953
2023-04-09 18:03:31,818 DEBUG   SenderThread:4936 [sender.py:send():303] send: summary
2023-04-09 18:03:31,818 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:03:31,819 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: check_version
2023-04-09 18:03:31,819 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: check_version
2023-04-09 18:03:32,149 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: run_start
2023-04-09 18:03:32,151 DEBUG   HandlerThread:4936 [system_info.py:__init__():31] System info init
2023-04-09 18:03:32,151 DEBUG   HandlerThread:4936 [system_info.py:__init__():46] System info init done
2023-04-09 18:03:32,151 INFO    HandlerThread:4936 [system_monitor.py:start():150] Starting system monitor
2023-04-09 18:03:32,152 INFO    SystemMonitor:4936 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-09 18:03:32,152 INFO    HandlerThread:4936 [system_monitor.py:probe():168] Collecting system info
2023-04-09 18:03:32,152 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started cpu
2023-04-09 18:03:32,153 DEBUG   HandlerThread:4936 [system_info.py:probe():195] Probing system
2023-04-09 18:03:32,153 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started disk
2023-04-09 18:03:32,153 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started gpuapple
2023-04-09 18:03:32,158 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started memory
2023-04-09 18:03:32,161 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started network
2023-04-09 18:03:32,162 DEBUG   HandlerThread:4936 [system_info.py:_probe_git():180] Probing git
2023-04-09 18:03:32,196 DEBUG   HandlerThread:4936 [system_info.py:_probe_git():188] Probing git done
2023-04-09 18:03:32,197 DEBUG   HandlerThread:4936 [system_info.py:probe():241] Probing system done
2023-04-09 18:03:32,197 DEBUG   HandlerThread:4936 [system_monitor.py:probe():177] {'os': 'macOS-12.6-arm64-arm-64bit', 'python': '3.9.16', 'heartbeatAt': '2023-04-09T16:03:32.153442', 'startedAt': '2023-04-09T16:03:24.354774', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': '<python with no main file>', 'git': {'remote': 'https://github.com/Christonikos/dynamic_risk.git', 'commit': '764d8a06ce1e62c3378d1d89bcb6e9a7b802923d'}, 'email': 'christonik@gmail.com', 'root': '/Users/christoszacharopoulos/projects/dynamic_risk', 'host': 'Christoss-MacBook-Air-2.local', 'username': 'christoszacharopoulos', 'executable': '/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'total': 228.27386474609375, 'used': 185.95089721679688}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2023-04-09 18:03:32,197 INFO    HandlerThread:4936 [system_monitor.py:probe():178] Finished collecting system info
2023-04-09 18:03:32,197 INFO    HandlerThread:4936 [system_monitor.py:probe():181] Publishing system info
2023-04-09 18:03:32,197 DEBUG   HandlerThread:4936 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-09 18:03:32,198 DEBUG   HandlerThread:4936 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-09 18:03:32,198 DEBUG   HandlerThread:4936 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-09 18:03:32,822 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/requirements.txt
2023-04-09 18:03:32,823 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/conda-environment.yaml
2023-04-09 18:03:32,823 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/wandb-summary.json
2023-04-09 18:03:33,310 DEBUG   HandlerThread:4936 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-09 18:03:33,311 INFO    HandlerThread:4936 [system_monitor.py:probe():183] Finished publishing system info
2023-04-09 18:03:33,311 DEBUG   SenderThread:4936 [sender.py:send():303] send: files
2023-04-09 18:03:33,311 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2023-04-09 18:03:33,316 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:03:33,316 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:03:33,393 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: pause
2023-04-09 18:03:33,393 INFO    HandlerThread:4936 [handler.py:handle_request_pause():696] stopping system metrics thread or process
2023-04-09 18:03:33,393 INFO    HandlerThread:4936 [system_monitor.py:finish():160] Stopping system monitor
2023-04-09 18:03:33,416 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-04-09 18:03:33,417 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-04-09 18:03:33,417 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined cpu
2023-04-09 18:03:33,417 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-04-09 18:03:33,417 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined disk
2023-04-09 18:03:33,417 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined gpuapple
2023-04-09 18:03:33,417 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined memory
2023-04-09 18:03:33,417 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined network
2023-04-09 18:03:33,618 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:03:33,619 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:03:33,619 DEBUG   SenderThread:4936 [sender.py:send():303] send: stats
2023-04-09 18:03:33,827 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/conda-environment.yaml
2023-04-09 18:03:33,828 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/output.log
2023-04-09 18:03:33,828 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/wandb-metadata.json
2023-04-09 18:03:34,292 INFO    Thread-52 :4936 [upload_job.py:push():143] Uploaded file /var/folders/nm/0bj88r1s27zgjf_kjcfv1gqh0000gn/T/tmp5s5t0rvmwandb/1x2kbgd2-wandb-metadata.json
2023-04-09 18:03:35,836 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/output.log
2023-04-09 18:03:48,617 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:03:48,618 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:04:02,935 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/config.yaml
2023-04-09 18:04:03,986 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:04:03,987 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:04:19,382 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:04:19,382 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:04:34,746 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:04:34,746 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:04:50,135 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:04:50,135 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:05:05,500 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:05:05,500 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:05:20,956 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:05:20,956 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:05:36,245 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:05:36,246 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:05:51,569 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:05:51,570 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:06:06,879 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:06:06,880 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:22:20,001 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:22:20,002 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:22:20,708 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f2b0>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/wdce65bh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 18:38:08,493 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:38:08,495 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:38:23,861 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:38:23,861 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:38:39,138 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:38:39,138 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:38:54,457 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:38:54,458 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:39:09,740 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:39:09,741 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:39:25,108 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:39:25,108 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:39:40,390 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:39:40,390 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:39:55,673 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:39:55,673 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:40:10,942 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:40:10,943 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:40:26,217 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:40:26,217 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:40:41,490 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:40:41,491 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:40:57,182 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:40:57,182 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:41:12,464 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:41:12,464 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:41:27,738 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:41:27,738 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:41:43,064 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:41:43,065 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:41:58,461 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:41:58,461 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:42:13,766 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:42:13,766 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:42:29,041 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:42:29,042 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:42:44,345 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:42:44,346 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:42:59,623 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:42:59,623 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:43:14,978 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:43:14,978 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:43:30,303 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:43:30,304 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:43:45,585 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:43:45,586 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:44:00,946 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:44:00,947 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:44:16,270 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:44:16,270 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:44:31,538 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:44:31,539 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:44:46,821 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:44:46,822 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:45:02,187 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:45:02,188 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:45:17,498 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:45:17,498 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:45:32,992 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:45:32,992 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:45:36,645 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: resume
2023-04-09 18:45:36,645 INFO    HandlerThread:4936 [handler.py:handle_request_resume():687] starting system metrics thread or process
2023-04-09 18:45:36,648 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: pause
2023-04-09 18:45:36,648 INFO    HandlerThread:4936 [handler.py:handle_request_pause():696] stopping system metrics thread or process
2023-04-09 18:45:48,326 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:45:48,326 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:46:03,862 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:46:03,862 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:46:19,336 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:46:19,337 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:46:34,853 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:46:34,854 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:46:50,342 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:46:50,343 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:47:05,659 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:47:05,659 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:47:20,978 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:47:20,978 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:47:36,262 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:47:36,262 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:47:49,232 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: resume
2023-04-09 18:47:49,233 INFO    HandlerThread:4936 [handler.py:handle_request_resume():687] starting system metrics thread or process
2023-04-09 18:47:49,278 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:47:49,279 DEBUG   SenderThread:4936 [sender.py:send():303] send: exit
2023-04-09 18:47:49,279 INFO    SenderThread:4936 [sender.py:send_exit():442] handling exit code: 0
2023-04-09 18:47:49,279 INFO    SenderThread:4936 [sender.py:send_exit():444] handling runtime: 1
2023-04-09 18:47:49,279 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:47:49,279 INFO    SenderThread:4936 [sender.py:send_exit():450] send defer
2023-04-09 18:47:49,280 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,280 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 0
2023-04-09 18:47:49,280 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,280 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 0
2023-04-09 18:47:49,280 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 1
2023-04-09 18:47:49,280 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,280 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 1
2023-04-09 18:47:49,280 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,280 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 1
2023-04-09 18:47:49,280 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 2
2023-04-09 18:47:49,281 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,281 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 2
2023-04-09 18:47:49,281 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,281 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 2
2023-04-09 18:47:49,281 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 3
2023-04-09 18:47:49,281 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,281 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 3
2023-04-09 18:47:49,281 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,281 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 3
2023-04-09 18:47:49,281 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 4
2023-04-09 18:47:49,281 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,281 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 4
2023-04-09 18:47:49,281 DEBUG   SenderThread:4936 [sender.py:send():303] send: summary
2023-04-09 18:47:49,282 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:47:49,282 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,282 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 4
2023-04-09 18:47:49,282 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 5
2023-04-09 18:47:49,282 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,282 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 5
2023-04-09 18:47:49,282 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,282 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 5
2023-04-09 18:47:49,573 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 6
2023-04-09 18:47:49,574 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:49,574 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 6
2023-04-09 18:47:49,574 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:49,574 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 6
2023-04-09 18:47:50,133 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/config.yaml
2023-04-09 18:47:50,133 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/wandb-summary.json
2023-04-09 18:47:50,134 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/output.log
2023-04-09 18:47:50,286 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: poll_exit
2023-04-09 18:47:51,899 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 7
2023-04-09 18:47:51,900 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: poll_exit
2023-04-09 18:47:51,900 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:51,901 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 7
2023-04-09 18:47:51,902 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:51,902 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 7
2023-04-09 18:47:51,903 INFO    SenderThread:4936 [dir_watcher.py:finish():362] shutting down directory watcher
2023-04-09 18:47:52,144 INFO    Thread-49 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/output.log
2023-04-09 18:47:52,146 INFO    SenderThread:4936 [dir_watcher.py:finish():392] scan: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files
2023-04-09 18:47:52,146 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/requirements.txt requirements.txt
2023-04-09 18:47:52,147 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/output.log output.log
2023-04-09 18:47:52,152 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/config.yaml config.yaml
2023-04-09 18:47:52,155 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/wandb-summary.json wandb-summary.json
2023-04-09 18:47:52,159 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/conda-environment.yaml conda-environment.yaml
2023-04-09 18:47:52,163 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/wandb-metadata.json wandb-metadata.json
2023-04-09 18:47:52,163 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 8
2023-04-09 18:47:52,164 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:52,164 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 8
2023-04-09 18:47:52,166 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:52,167 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 8
2023-04-09 18:47:52,167 INFO    SenderThread:4936 [file_pusher.py:finish():168] shutting down file pusher
2023-04-09 18:47:53,079 INFO    Thread-53 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/requirements.txt
2023-04-09 18:47:53,081 INFO    Thread-55 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/config.yaml
2023-04-09 18:47:53,082 INFO    Thread-57 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/conda-environment.yaml
2023-04-09 18:47:53,083 INFO    Thread-54 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/output.log
2023-04-09 18:47:53,085 INFO    Thread-56 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/files/wandb-summary.json
2023-04-09 18:47:53,291 INFO    Thread-48 :4936 [sender.py:transition_state():463] send defer: 9
2023-04-09 18:47:53,292 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:53,292 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 9
2023-04-09 18:47:53,293 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:53,293 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 9
2023-04-09 18:47:53,293 INFO    SenderThread:4936 [file_pusher.py:join():173] waiting for file pusher
2023-04-09 18:47:53,293 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 10
2023-04-09 18:47:53,294 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:53,294 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 10
2023-04-09 18:47:53,294 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:53,294 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 10
2023-04-09 18:47:53,929 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 11
2023-04-09 18:47:53,930 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:53,930 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 11
2023-04-09 18:47:53,931 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:53,931 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 11
2023-04-09 18:47:53,931 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 12
2023-04-09 18:47:53,932 DEBUG   SenderThread:4936 [sender.py:send():303] send: final
2023-04-09 18:47:53,932 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:47:53,932 DEBUG   SenderThread:4936 [sender.py:send():303] send: footer
2023-04-09 18:47:53,932 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 12
2023-04-09 18:47:53,932 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:47:53,933 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 12
2023-04-09 18:47:53,934 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: poll_exit
2023-04-09 18:47:53,935 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: server_info
2023-04-09 18:47:53,935 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: poll_exit
2023-04-09 18:47:53,935 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: get_summary
2023-04-09 18:47:53,935 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: server_info
2023-04-09 18:47:53,936 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: sampled_history
2023-04-09 18:47:54,544 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: shutdown
2023-04-09 18:47:54,544 INFO    HandlerThread:4936 [handler.py:finish():814] shutting down handler
2023-04-09 18:47:54,937 INFO    WriterThread:4936 [datastore.py:close():279] close: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_180324-wdce65bh/run-wdce65bh.wandb
2023-04-09 18:47:55,546 INFO    SenderThread:4936 [sender.py:finish():1331] shutting down sender
2023-04-09 18:47:55,546 INFO    SenderThread:4936 [file_pusher.py:finish():168] shutting down file pusher
2023-04-09 18:47:55,547 INFO    SenderThread:4936 [file_pusher.py:join():173] waiting for file pusher
2023-04-09 18:47:56,553 INFO    StreamThr :4936 [internal.py:wandb_internal():88] W&B internal server running at pid: 4936, started at: 2023-04-09 18:47:56.551975
2023-04-09 18:47:56,555 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: status
2023-04-09 18:47:56,557 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: status
2023-04-09 18:47:56,558 INFO    WriterThread:4936 [datastore.py:open_for_write():75] open: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/run-t66mwbv5.wandb
2023-04-09 18:47:56,558 DEBUG   SenderThread:4936 [sender.py:send():303] send: header
2023-04-09 18:47:56,558 DEBUG   SenderThread:4936 [sender.py:send():303] send: run
2023-04-09 18:47:57,184 INFO    SenderThread:4936 [dir_watcher.py:__init__():216] watching files in: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files
2023-04-09 18:47:57,185 INFO    SenderThread:4936 [sender.py:_start_run_threads():928] run started: t66mwbv5 with start time 1681058875.561468
2023-04-09 18:47:57,185 DEBUG   SenderThread:4936 [sender.py:send():303] send: summary
2023-04-09 18:47:57,185 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:47:57,186 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: check_version
2023-04-09 18:47:57,186 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: check_version
2023-04-09 18:47:57,507 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: run_start
2023-04-09 18:47:57,508 DEBUG   HandlerThread:4936 [system_info.py:__init__():31] System info init
2023-04-09 18:47:57,508 DEBUG   HandlerThread:4936 [system_info.py:__init__():46] System info init done
2023-04-09 18:47:57,509 INFO    HandlerThread:4936 [system_monitor.py:start():150] Starting system monitor
2023-04-09 18:47:57,509 INFO    SystemMonitor:4936 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-09 18:47:57,509 INFO    HandlerThread:4936 [system_monitor.py:probe():168] Collecting system info
2023-04-09 18:47:57,509 DEBUG   HandlerThread:4936 [system_info.py:probe():195] Probing system
2023-04-09 18:47:57,509 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started cpu
2023-04-09 18:47:57,510 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started disk
2023-04-09 18:47:57,510 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started gpuapple
2023-04-09 18:47:57,513 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started memory
2023-04-09 18:47:57,515 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started network
2023-04-09 18:47:57,516 DEBUG   HandlerThread:4936 [system_info.py:_probe_git():180] Probing git
2023-04-09 18:47:57,544 DEBUG   HandlerThread:4936 [system_info.py:_probe_git():188] Probing git done
2023-04-09 18:47:57,544 DEBUG   HandlerThread:4936 [system_info.py:probe():241] Probing system done
2023-04-09 18:47:57,544 DEBUG   HandlerThread:4936 [system_monitor.py:probe():177] {'os': 'macOS-12.6-arm64-arm-64bit', 'python': '3.9.16', 'heartbeatAt': '2023-04-09T16:47:57.509954', 'startedAt': '2023-04-09T16:47:49.275928', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': '<python with no main file>', 'git': {'remote': 'https://github.com/Christonikos/dynamic_risk.git', 'commit': '764d8a06ce1e62c3378d1d89bcb6e9a7b802923d'}, 'email': 'christonik@gmail.com', 'root': '/Users/christoszacharopoulos/projects/dynamic_risk', 'host': 'Christoss-MacBook-Air-2.local', 'username': 'christoszacharopoulos', 'executable': '/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'total': 228.27386474609375, 'used': 185.95697402954102}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2023-04-09 18:47:57,544 INFO    HandlerThread:4936 [system_monitor.py:probe():178] Finished collecting system info
2023-04-09 18:47:57,545 INFO    HandlerThread:4936 [system_monitor.py:probe():181] Publishing system info
2023-04-09 18:47:57,545 DEBUG   HandlerThread:4936 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-09 18:47:57,545 DEBUG   HandlerThread:4936 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-09 18:47:57,545 DEBUG   HandlerThread:4936 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-09 18:47:58,188 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/conda-environment.yaml
2023-04-09 18:47:58,188 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/wandb-summary.json
2023-04-09 18:47:58,188 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/requirements.txt
2023-04-09 18:47:58,685 DEBUG   HandlerThread:4936 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-09 18:47:58,686 INFO    HandlerThread:4936 [system_monitor.py:probe():183] Finished publishing system info
2023-04-09 18:47:58,686 DEBUG   SenderThread:4936 [sender.py:send():303] send: files
2023-04-09 18:47:58,686 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2023-04-09 18:47:58,691 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:47:58,691 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:47:58,976 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:47:59,193 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/conda-environment.yaml
2023-04-09 18:47:59,193 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/wandb-metadata.json
2023-04-09 18:47:59,193 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/output.log
2023-04-09 18:47:59,411 INFO    Thread-70 :4936 [upload_job.py:push():143] Uploaded file /var/folders/nm/0bj88r1s27zgjf_kjcfv1gqh0000gn/T/tmpe8rt482kwandb/14qi2gsb-wandb-metadata.json
2023-04-09 18:48:01,198 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/output.log
2023-04-09 18:48:13,984 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:48:13,985 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:48:21,973 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:48:21,974 DEBUG   SenderThread:4936 [sender.py:send():303] send: exit
2023-04-09 18:48:21,974 INFO    SenderThread:4936 [sender.py:send_exit():442] handling exit code: 0
2023-04-09 18:48:21,974 INFO    SenderThread:4936 [sender.py:send_exit():444] handling runtime: 24
2023-04-09 18:48:21,975 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:48:21,976 INFO    SenderThread:4936 [sender.py:send_exit():450] send defer
2023-04-09 18:48:21,976 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:21,976 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 0
2023-04-09 18:48:21,976 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:21,976 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 0
2023-04-09 18:48:21,976 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 1
2023-04-09 18:48:21,977 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:21,977 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 1
2023-04-09 18:48:21,977 INFO    HandlerThread:4936 [system_monitor.py:finish():160] Stopping system monitor
2023-04-09 18:48:21,997 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-04-09 18:48:21,997 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-04-09 18:48:21,998 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined cpu
2023-04-09 18:48:21,998 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-04-09 18:48:21,998 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined disk
2023-04-09 18:48:22,251 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined gpuapple
2023-04-09 18:48:22,251 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined memory
2023-04-09 18:48:22,251 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined network
2023-04-09 18:48:22,251 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:22,251 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 1
2023-04-09 18:48:22,251 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 2
2023-04-09 18:48:22,251 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:48:22,251 DEBUG   SenderThread:4936 [sender.py:send():303] send: stats
2023-04-09 18:48:22,251 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:22,252 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 2
2023-04-09 18:48:22,252 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:22,252 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 2
2023-04-09 18:48:22,252 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 3
2023-04-09 18:48:22,252 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:22,252 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 3
2023-04-09 18:48:22,252 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:22,252 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 3
2023-04-09 18:48:22,252 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 4
2023-04-09 18:48:22,252 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:22,252 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 4
2023-04-09 18:48:22,252 DEBUG   SenderThread:4936 [sender.py:send():303] send: summary
2023-04-09 18:48:22,252 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:48:22,253 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:22,253 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 4
2023-04-09 18:48:22,253 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 5
2023-04-09 18:48:22,253 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:22,253 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 5
2023-04-09 18:48:22,253 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:22,253 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 5
2023-04-09 18:48:22,305 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/wandb-summary.json
2023-04-09 18:48:22,790 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 6
2023-04-09 18:48:22,790 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:22,790 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 6
2023-04-09 18:48:22,791 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:22,791 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 6
2023-04-09 18:48:22,981 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: poll_exit
2023-04-09 18:48:23,310 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/config.yaml
2023-04-09 18:48:23,311 INFO    Thread-67 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/output.log
2023-04-09 18:48:25,035 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 7
2023-04-09 18:48:25,036 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: poll_exit
2023-04-09 18:48:25,037 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:25,038 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 7
2023-04-09 18:48:25,039 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:25,039 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 7
2023-04-09 18:48:25,039 INFO    SenderThread:4936 [dir_watcher.py:finish():362] shutting down directory watcher
2023-04-09 18:48:25,319 INFO    SenderThread:4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/output.log
2023-04-09 18:48:25,320 INFO    SenderThread:4936 [dir_watcher.py:finish():392] scan: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files
2023-04-09 18:48:25,320 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/requirements.txt requirements.txt
2023-04-09 18:48:25,321 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/output.log output.log
2023-04-09 18:48:25,328 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/config.yaml config.yaml
2023-04-09 18:48:25,332 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/wandb-summary.json wandb-summary.json
2023-04-09 18:48:25,335 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/conda-environment.yaml conda-environment.yaml
2023-04-09 18:48:25,339 INFO    SenderThread:4936 [dir_watcher.py:finish():406] scan save: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/wandb-metadata.json wandb-metadata.json
2023-04-09 18:48:25,340 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 8
2023-04-09 18:48:25,343 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:25,343 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 8
2023-04-09 18:48:25,343 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:25,344 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 8
2023-04-09 18:48:25,344 INFO    SenderThread:4936 [file_pusher.py:finish():168] shutting down file pusher
2023-04-09 18:48:26,094 INFO    Thread-72 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/output.log
2023-04-09 18:48:26,247 INFO    Thread-73 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/config.yaml
2023-04-09 18:48:26,249 INFO    Thread-74 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/wandb-summary.json
2023-04-09 18:48:26,249 INFO    Thread-71 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/requirements.txt
2023-04-09 18:48:26,249 INFO    Thread-75 :4936 [upload_job.py:push():143] Uploaded file /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/files/conda-environment.yaml
2023-04-09 18:48:26,455 INFO    Thread-66 :4936 [sender.py:transition_state():463] send defer: 9
2023-04-09 18:48:26,456 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:26,457 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 9
2023-04-09 18:48:26,457 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:26,457 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 9
2023-04-09 18:48:26,458 INFO    SenderThread:4936 [file_pusher.py:join():173] waiting for file pusher
2023-04-09 18:48:26,458 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 10
2023-04-09 18:48:26,458 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:26,459 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 10
2023-04-09 18:48:26,459 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:26,459 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 10
2023-04-09 18:48:26,658 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 11
2023-04-09 18:48:26,659 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:26,660 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 11
2023-04-09 18:48:26,660 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:26,660 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 11
2023-04-09 18:48:26,661 INFO    SenderThread:4936 [sender.py:transition_state():463] send defer: 12
2023-04-09 18:48:26,661 DEBUG   SenderThread:4936 [sender.py:send():303] send: final
2023-04-09 18:48:26,662 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: defer
2023-04-09 18:48:26,662 DEBUG   SenderThread:4936 [sender.py:send():303] send: footer
2023-04-09 18:48:26,662 INFO    HandlerThread:4936 [handler.py:handle_request_defer():162] handle defer: 12
2023-04-09 18:48:26,662 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: defer
2023-04-09 18:48:26,663 INFO    SenderThread:4936 [sender.py:send_request_defer():459] handle sender defer: 12
2023-04-09 18:48:26,665 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: poll_exit
2023-04-09 18:48:26,665 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: poll_exit
2023-04-09 18:48:26,665 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: server_info
2023-04-09 18:48:26,666 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: get_summary
2023-04-09 18:48:26,666 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: server_info
2023-04-09 18:48:26,667 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: sampled_history
2023-04-09 18:48:27,472 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: shutdown
2023-04-09 18:48:27,473 INFO    HandlerThread:4936 [handler.py:finish():814] shutting down handler
2023-04-09 18:48:27,666 INFO    WriterThread:4936 [datastore.py:close():279] close: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184749-t66mwbv5/run-t66mwbv5.wandb
2023-04-09 18:48:28,475 INFO    SenderThread:4936 [sender.py:finish():1331] shutting down sender
2023-04-09 18:48:28,475 INFO    SenderThread:4936 [file_pusher.py:finish():168] shutting down file pusher
2023-04-09 18:48:28,476 INFO    SenderThread:4936 [file_pusher.py:join():173] waiting for file pusher
2023-04-09 18:48:29,481 INFO    StreamThr :4936 [internal.py:wandb_internal():88] W&B internal server running at pid: 4936, started at: 2023-04-09 18:48:29.479887
2023-04-09 18:48:29,483 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: status
2023-04-09 18:48:29,485 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: status
2023-04-09 18:48:29,486 DEBUG   SenderThread:4936 [sender.py:send():303] send: header
2023-04-09 18:48:29,487 INFO    WriterThread:4936 [datastore.py:open_for_write():75] open: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/run-zahp52q6.wandb
2023-04-09 18:48:29,487 DEBUG   SenderThread:4936 [sender.py:send():303] send: run
2023-04-09 18:48:30,372 INFO    SenderThread:4936 [dir_watcher.py:__init__():216] watching files in: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files
2023-04-09 18:48:30,372 INFO    SenderThread:4936 [sender.py:_start_run_threads():928] run started: zahp52q6 with start time 1681058908.489806
2023-04-09 18:48:30,373 DEBUG   SenderThread:4936 [sender.py:send():303] send: summary
2023-04-09 18:48:30,373 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: check_version
2023-04-09 18:48:30,373 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-09 18:48:30,374 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: check_version
2023-04-09 18:48:30,762 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: run_start
2023-04-09 18:48:30,764 DEBUG   HandlerThread:4936 [system_info.py:__init__():31] System info init
2023-04-09 18:48:30,764 DEBUG   HandlerThread:4936 [system_info.py:__init__():46] System info init done
2023-04-09 18:48:30,765 INFO    HandlerThread:4936 [system_monitor.py:start():150] Starting system monitor
2023-04-09 18:48:30,765 INFO    SystemMonitor:4936 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-09 18:48:30,765 INFO    HandlerThread:4936 [system_monitor.py:probe():168] Collecting system info
2023-04-09 18:48:30,765 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started cpu
2023-04-09 18:48:30,766 DEBUG   HandlerThread:4936 [system_info.py:probe():195] Probing system
2023-04-09 18:48:30,766 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started disk
2023-04-09 18:48:30,767 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started gpuapple
2023-04-09 18:48:30,773 DEBUG   HandlerThread:4936 [system_info.py:_probe_git():180] Probing git
2023-04-09 18:48:30,775 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started memory
2023-04-09 18:48:30,776 INFO    SystemMonitor:4936 [interfaces.py:start():168] Started network
2023-04-09 18:48:30,809 DEBUG   HandlerThread:4936 [system_info.py:_probe_git():188] Probing git done
2023-04-09 18:48:30,810 DEBUG   HandlerThread:4936 [system_info.py:probe():241] Probing system done
2023-04-09 18:48:30,810 DEBUG   HandlerThread:4936 [system_monitor.py:probe():177] {'os': 'macOS-12.6-arm64-arm-64bit', 'python': '3.9.16', 'heartbeatAt': '2023-04-09T16:48:30.766676', 'startedAt': '2023-04-09T16:48:21.970942', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': '<python with no main file>', 'git': {'remote': 'https://github.com/Christonikos/dynamic_risk.git', 'commit': '764d8a06ce1e62c3378d1d89bcb6e9a7b802923d'}, 'email': 'christonik@gmail.com', 'root': '/Users/christoszacharopoulos/projects/dynamic_risk', 'host': 'Christoss-MacBook-Air-2.local', 'username': 'christoszacharopoulos', 'executable': '/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'total': 228.27386474609375, 'used': 185.9572296142578}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2023-04-09 18:48:30,810 INFO    HandlerThread:4936 [system_monitor.py:probe():178] Finished collecting system info
2023-04-09 18:48:30,810 INFO    HandlerThread:4936 [system_monitor.py:probe():181] Publishing system info
2023-04-09 18:48:30,810 DEBUG   HandlerThread:4936 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-09 18:48:30,811 DEBUG   HandlerThread:4936 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-09 18:48:30,811 DEBUG   HandlerThread:4936 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-09 18:48:31,378 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/conda-environment.yaml
2023-04-09 18:48:31,378 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/wandb-summary.json
2023-04-09 18:48:31,378 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/requirements.txt
2023-04-09 18:48:31,877 DEBUG   HandlerThread:4936 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-09 18:48:31,878 INFO    HandlerThread:4936 [system_monitor.py:probe():183] Finished publishing system info
2023-04-09 18:48:31,878 DEBUG   SenderThread:4936 [sender.py:send():303] send: files
2023-04-09 18:48:31,878 INFO    SenderThread:4936 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2023-04-09 18:48:31,883 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:48:31,883 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:48:31,961 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: pause
2023-04-09 18:48:31,961 INFO    HandlerThread:4936 [handler.py:handle_request_pause():696] stopping system metrics thread or process
2023-04-09 18:48:31,961 INFO    HandlerThread:4936 [system_monitor.py:finish():160] Stopping system monitor
2023-04-09 18:48:31,981 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-04-09 18:48:31,981 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-04-09 18:48:31,981 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined cpu
2023-04-09 18:48:31,981 DEBUG   SystemMonitor:4936 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-04-09 18:48:31,981 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined disk
2023-04-09 18:48:31,982 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined gpuapple
2023-04-09 18:48:31,982 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined memory
2023-04-09 18:48:31,982 INFO    HandlerThread:4936 [interfaces.py:finish():173] Joined network
2023-04-09 18:48:32,386 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:48:32,390 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/conda-environment.yaml
2023-04-09 18:48:32,390 DEBUG   SenderThread:4936 [sender.py:send():303] send: telemetry
2023-04-09 18:48:32,390 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/wandb-metadata.json
2023-04-09 18:48:32,391 DEBUG   SenderThread:4936 [sender.py:send():303] send: stats
2023-04-09 18:48:32,855 INFO    Thread-88 :4936 [upload_job.py:push():143] Uploaded file /var/folders/nm/0bj88r1s27zgjf_kjcfv1gqh0000gn/T/tmpz8nokszfwandb/36lk2vki-wandb-metadata.json
2023-04-09 18:48:33,395 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_created():275] file/dir created: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/output.log
2023-04-09 18:48:34,401 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/output.log
2023-04-09 18:48:47,395 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:48:47,396 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:49:00,525 INFO    Thread-85 :4936 [dir_watcher.py:_on_file_modified():292] file/dir modified: /Users/christoszacharopoulos/projects/dynamic_risk/src/wandb/run-20230409_184821-zahp52q6/files/config.yaml
2023-04-09 18:49:02,863 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:49:02,864 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:49:18,224 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:49:18,225 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:49:33,622 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:49:33,623 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:49:49,023 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:49:49,024 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:50:04,382 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:50:04,383 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:50:19,750 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:50:19,752 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:50:35,052 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:50:35,053 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:50:50,429 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:50:50,429 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:51:05,706 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:51:05,707 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:51:21,062 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:51:21,062 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:51:36,409 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:51:36,410 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:51:51,705 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:51:51,706 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:52:07,104 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:52:07,105 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:52:22,463 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:52:22,464 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:52:37,785 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:52:37,785 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:52:53,100 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:52:53,101 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:53:08,432 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:53:08,432 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 18:55:28,680 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 18:55:28,681 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 19:10:27,693 ERROR   SenderThread:4936 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11da5e7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da5e7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da5e7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-04-09 19:10:27,707 WARNING SenderThread:4936 [sender.py:send_request_stop_status():383] Failed to check stop requested status: [Errno 32] Broken pipe
2023-04-09 19:10:28,948 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f070>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 19:10:30,958 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da617f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f070>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 19:10:35,221 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da1e580>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f070>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 19:28:15,411 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 19:28:15,412 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 19:28:17,544 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da5e4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f070>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 19:28:18,950 ERROR   SenderThread:4936 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11c51c280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11c51c280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11c51c280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-04-09 19:28:18,952 WARNING SenderThread:4936 [sender.py:send_request_stop_status():383] Failed to check stop requested status: [Errno 32] Broken pipe
2023-04-09 20:02:24,585 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 20:02:24,586 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 20:02:24,708 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da5e160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f070>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 20:02:28,221 ERROR   SenderThread:4936 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11da13910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da13910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da13910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-04-09 20:02:28,222 WARNING SenderThread:4936 [sender.py:send_request_stop_status():383] Failed to check stop requested status: [Errno 32] Broken pipe
2023-04-09 20:09:24,533 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 20:09:24,534 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 20:14:41,693 ERROR   SenderThread:4936 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x11da00610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da00610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/christoszacharopoulos/anaconda3/envs/dynamic_risk/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11da00610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-04-09 20:14:41,695 WARNING SenderThread:4936 [sender.py:send_request_stop_status():383] Failed to check stop requested status: [Errno 32] Broken pipe
2023-04-09 20:30:38,004 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 20:30:38,005 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 21:14:03,569 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 21:14:03,569 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 21:14:18,747 DEBUG   HandlerThread:4936 [handler.py:handle_request():139] handle_request: stop_status
2023-04-09 21:14:18,748 DEBUG   SenderThread:4936 [sender.py:send_request():317] send_request: stop_status
2023-04-09 21:14:19,566 WARNING FileStreamThread:4936 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x11c50f070>>, args: ('https://api.wandb.ai/files/christonikos/dynamic_risk_assesment/zahp52q6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-04-09 21:14:25,428 DEBUG   SenderThread:4936 [sender.py:send():303] send: exit
2023-04-09 21:14:25,428 INFO    SenderThread:4936 [sender.py:send_exit():442] handling exit code: 0
2023-04-09 21:14:25,428 INFO    SenderThread:4936 [sender.py:send_exit():444] handling runtime: 1
